base: libp11: refresh patches on 0.4.13
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

diff --git a/meta-lmp-base/recipes-support/libp11/libp11/0001-from-list-Introduce-generic-keypair-generation-inter.patch b/meta-lmp-base/recipes-support/libp11/libp11/0001-from-list-Introduce-generic-keypair-generation-inter.patch
--- a/meta-lmp-base/recipes-support/libp11/libp11/0001-from-list-Introduce-generic-keypair-generation-inter.patch
+++ b/meta-lmp-base/recipes-support/libp11/libp11/0001-from-list-Introduce-generic-keypair-generation-inter.patch
@@ -36,29 +36,31 @@ Code for ECC keygen was taken from:
 https://github.com/OpenSC/libp11/pull/379 and reworked to compile and
 work with some new additions to libp11 i.e. templates.
 
-Upstream-Status: Submitted [https://github.com/OpenSC/libp11/pull/474]
+Upstream-Status: Backport [https://github.com/OpenSC/libp11/pull/474]
 Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
 ---
- src/eng_back.c       |  60 +++++++++++++
- src/eng_front.c      |   4 +
- src/engine.h         |   1 +
- src/libp11-int.h     |  15 ++--
- src/libp11.h         |  45 ++++++----
- src/p11_front.c      |  30 +++++--
- src/p11_key.c        |  94 +++++++++++++++++++-
- src/p11_misc.c       |  75 ++++++++++++++++
- tests/Makefile.am    |   6 +-
- tests/keygen.c       | 206 +++++++++++++++++++++++++++++++++++++++++++
- tests/keygen.softhsm |  39 ++++++++
- 11 files changed, 544 insertions(+), 31 deletions(-)
+ src/eng_back.c        |  60 ++++++++++++
+ src/eng_front.c       |   4 +
+ src/engine.h          |   1 +
+ src/libp11-int.h      |  13 ++-
+ src/libp11.h          |  46 ++++++----
+ src/p11_front.c       |  30 ++++--
+ src/p11_key.c         |  94 ++++++++++++++++++-
+ src/p11_misc.c        |  75 +++++++++++++++
+ tests/Makefile.am     |   4 +-
+ tests/ec-no-pubkey.sh | 122 +++++++++++++++++++++++++
+ tests/keygen.c        | 206 ++++++++++++++++++++++++++++++++++++++++++
+ tests/keygen.softhsm  |  39 ++++++++
+ 12 files changed, 664 insertions(+), 30 deletions(-)
+ create mode 100644 tests/ec-no-pubkey.sh
  create mode 100644 tests/keygen.c
  create mode 100755 tests/keygen.softhsm
 
 diff --git a/src/eng_back.c b/src/eng_back.c
-index d25e3c1..b823950 100644
+index 5dc6dad..ac83593 100644
 --- a/src/eng_back.c
 +++ b/src/eng_back.c
-@@ -890,6 +890,64 @@ EVP_PKEY *ctx_load_privkey(ENGINE_CTX *ctx, const char *s_key_id,
+@@ -1031,6 +1031,64 @@ EVP_PKEY *ctx_load_privkey(ENGINE_CTX *ctx, const char *s_key_id,
  	return PKCS11_get_private_key(key);
  }
  
@@ -123,20 +125,20 @@ index d25e3c1..b823950 100644
  /******************************************************************************/
  /* Engine ctrl request handling                                               */
  /******************************************************************************/
-@@ -1008,6 +1066,8 @@ int ctx_engine_ctrl(ENGINE_CTX *ctx, int cmd, long i, void *p, void (*f)())
+@@ -1149,6 +1207,8 @@ int ctx_engine_ctrl(ENGINE_CTX *ctx, int cmd, long i, void *p, void (*f)())
  		return ctx_ctrl_force_login(ctx);
  	case CMD_RE_ENUMERATE:
- 		return ctx_enumerate_slots(ctx, ctx->pkcs11_ctx);
+ 		return ctx_enumerate_slots(ctx);
 +	case CMD_KEYGEN:
 +		return ctx_keygen(ctx, p);
  	default:
  		ENGerr(ENG_F_CTX_ENGINE_CTRL, ENG_R_UNKNOWN_COMMAND);
  		break;
 diff --git a/src/eng_front.c b/src/eng_front.c
-index 3a3c891..e3e5a78 100644
+index 994077c..39a7b1c 100644
 --- a/src/eng_front.c
 +++ b/src/eng_front.c
-@@ -79,6 +79,10 @@ static const ENGINE_CMD_DEFN engine_cmd_defns[] = {
+@@ -80,6 +80,10 @@ static const ENGINE_CMD_DEFN engine_cmd_defns[] = {
  		"RE_ENUMERATE",
  		"re enumerate slots",
  		ENGINE_CMD_FLAG_NO_INPUT},
@@ -148,10 +150,10 @@ index 3a3c891..e3e5a78 100644
  };
  
 diff --git a/src/engine.h b/src/engine.h
-index 54bdcf0..740f86e 100644
+index 05296a6..dd07ed7 100644
 --- a/src/engine.h
 +++ b/src/engine.h
-@@ -52,6 +52,7 @@
+@@ -56,6 +56,7 @@
  #define CMD_SET_CALLBACK_DATA	(ENGINE_CMD_BASE + 8)
  #define CMD_FORCE_LOGIN	(ENGINE_CMD_BASE+9)
  #define CMD_RE_ENUMERATE	(ENGINE_CMD_BASE+10)
@@ -160,10 +162,10 @@ index 54bdcf0..740f86e 100644
  typedef struct st_engine_ctx ENGINE_CTX; /* opaque */
  
 diff --git a/src/libp11-int.h b/src/libp11-int.h
-index 2d4c48a..ddde598 100644
+index fd84f97..d5a4c8a 100644
 --- a/src/libp11-int.h
 +++ b/src/libp11-int.h
-@@ -125,6 +125,9 @@ extern int ERR_load_CKR_strings(void);
+@@ -130,6 +130,9 @@ extern int ERR_load_CKR_strings(void);
  	pkcs11_strdup((char *) s, sizeof(s))
  extern char *pkcs11_strdup(char *, size_t);
  
@@ -173,16 +175,13 @@ index 2d4c48a..ddde598 100644
  /* Emulate the OpenSSL 1.1 getters */
  #if OPENSSL_VERSION_NUMBER < 0x10100003L || ( defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER < 0x3000000L )
  #define EVP_PKEY_get0_RSA(key) ((key)->pkey.rsa)
-@@ -307,12 +310,14 @@ extern int pkcs11_store_certificate(PKCS11_SLOT_private *, X509 * x509,
- extern int pkcs11_seed_random(PKCS11_SLOT_private *, const unsigned char *s, unsigned int s_len);
- extern int pkcs11_generate_random(PKCS11_SLOT_private *, unsigned char *r, unsigned int r_len);
+@@ -319,9 +322,13 @@ extern int pkcs11_generate_random(PKCS11_SLOT_private *, unsigned char *r, unsig
+ /* Internal implementation of deprecated features */
  
--/* Internal implementation of deprecated features */
--
  /* Generate and store a private key on the token */
 -extern int pkcs11_generate_key(PKCS11_SLOT_private *tpriv,
 -	int algorithm, unsigned int bits,
--	char *label, unsigned char* id, size_t id_len);
+-	char *label, unsigned char *id, size_t id_len);
 +extern int pkcs11_rsa_keygen(PKCS11_SLOT_private *tpriv,
 +	unsigned int bits, char *label, unsigned char* id, size_t id_len);
 +
@@ -194,10 +193,10 @@ index 2d4c48a..ddde598 100644
  /* Get the RSA key modulus size (in bytes) */
  extern int pkcs11_get_key_size(PKCS11_OBJECT_private *);
 diff --git a/src/libp11.h b/src/libp11.h
-index bd47d67..27a34ec 100644
+index 8d16560..b177236 100644
 --- a/src/libp11.h
 +++ b/src/libp11.h
-@@ -111,6 +111,25 @@ typedef struct PKCS11_ctx_st {
+@@ -106,6 +106,25 @@ typedef struct PKCS11_ctx_st {
  	void *_private;
  } PKCS11_CTX;
  
@@ -223,7 +222,7 @@ index bd47d67..27a34ec 100644
  /**
   * Create a new libp11 context
   *
-@@ -387,6 +406,17 @@ extern int PKCS11_store_certificate(PKCS11_TOKEN * token, X509 * x509,
+@@ -394,6 +413,17 @@ extern int PKCS11_store_certificate(PKCS11_TOKEN *token, X509 *x509,
  		char *label, unsigned char *id, size_t id_len,
  		PKCS11_CERT **ret_cert);
  
@@ -241,7 +240,7 @@ index bd47d67..27a34ec 100644
  /* Access the random number generator */
  extern int PKCS11_seed_random(PKCS11_SLOT *slot, const unsigned char *s, unsigned int s_len);
  extern int PKCS11_generate_random(PKCS11_SLOT *slot, unsigned char *r, unsigned int r_len);
-@@ -443,21 +473,6 @@ extern void ERR_load_PKCS11_strings(void);
+@@ -428,22 +458,6 @@ extern void ERR_load_PKCS11_strings(void);
   * duplicate the functionality OpenSSL provides for EVP_PKEY objects
   */
  
@@ -257,14 +256,15 @@ index bd47d67..27a34ec 100644
 - * @retval 0 success
 - * @retval -1 error
 - */
--P11_DEPRECATED_FUNC extern int PKCS11_generate_key(PKCS11_TOKEN * token,
+-extern int PKCS11_generate_key(PKCS11_TOKEN *token,
 -	int algorithm, unsigned int bits,
--	char *label, unsigned char* id, size_t id_len);
- 
+-	char *label, unsigned char *id, size_t id_len);
+-
  /* Get the RSA key modulus size (in bytes) */
- P11_DEPRECATED_FUNC extern int PKCS11_get_key_size(PKCS11_KEY *);
+ extern int PKCS11_get_key_size(PKCS11_KEY *);
+ 
 diff --git a/src/p11_front.c b/src/p11_front.c
-index f74f209..b0072cf 100644
+index c278fd6..90a829e 100644
 --- a/src/p11_front.c
 +++ b/src/p11_front.c
 @@ -16,6 +16,8 @@
@@ -276,7 +276,7 @@ index f74f209..b0072cf 100644
  #include "libp11-int.h"
  
  /* The following exported functions are *not* implemented here:
-@@ -367,18 +369,34 @@ int PKCS11_set_ui_method(PKCS11_CTX *pctx, UI_METHOD *ui_method, void *ui_user_d
+@@ -399,18 +401,34 @@ int PKCS11_set_ui_method(PKCS11_CTX *pctx, UI_METHOD *ui_method, void *ui_user_d
  	return pkcs11_set_ui_method(ctx, ui_method, ui_user_data);
  }
  
@@ -318,19 +318,19 @@ index f74f209..b0072cf 100644
  {
  	PKCS11_OBJECT_private *key = PRIVKEY(pkey);
 diff --git a/src/p11_key.c b/src/p11_key.c
-index ec7f279..62f68a4 100644
+index d1afd7a..d131a74 100644
 --- a/src/p11_key.c
 +++ b/src/p11_key.c
-@@ -252,7 +252,7 @@ int pkcs11_reload_object(PKCS11_OBJECT_private *obj)
+@@ -258,7 +258,7 @@ int pkcs11_reload_object(PKCS11_OBJECT_private *obj)
  /**
   * Generate a key pair directly on token
   */
 -int pkcs11_generate_key(PKCS11_SLOT_private *slot, int algorithm, unsigned int bits,
 +int pkcs11_rsa_keygen(PKCS11_SLOT_private *slot, unsigned int bits,
- 		char *label, unsigned char* id, size_t id_len) {
+ 		char *label, unsigned char *id, size_t id_len) {
  
  	PKCS11_CTX_private *ctx = slot->ctx;
-@@ -266,10 +266,8 @@ int pkcs11_generate_key(PKCS11_SLOT_private *slot, int algorithm, unsigned int b
+@@ -272,10 +272,8 @@ int pkcs11_generate_key(PKCS11_SLOT_private *slot, int algorithm, unsigned int b
  	CK_OBJECT_HANDLE pub_key_obj, priv_key_obj;
  	int rv;
  
@@ -342,7 +342,7 @@ index ec7f279..62f68a4 100644
  
  	/* pubkey attributes */
  	pkcs11_addattr(&pubtmpl, CKA_ID, id, id_len);
-@@ -310,6 +308,94 @@ int pkcs11_generate_key(PKCS11_SLOT_private *slot, int algorithm, unsigned int b
+@@ -316,6 +314,94 @@ int pkcs11_generate_key(PKCS11_SLOT_private *slot, int algorithm, unsigned int b
  	return 0;
  }
  
@@ -522,29 +522,155 @@ index 1b0e64d..1d9a845 100644
 +
  /* vim: set noexpandtab: */
 diff --git a/tests/Makefile.am b/tests/Makefile.am
-index b1bc0fb..d0e36b8 100644
+index a3d668d..ebb4976 100644
 --- a/tests/Makefile.am
 +++ b/tests/Makefile.am
-@@ -18,6 +18,8 @@ check_PROGRAMS = \
+@@ -18,7 +18,8 @@ check_PROGRAMS = \
  	rsa-oaep \
  	check-privkey \
- 	store-cert
+ 	store-cert \
+-	dup-key
 +	dup-key \
 +	keygen
  dist_check_SCRIPTS = \
  	rsa-testpkcs11.softhsm \
  	rsa-testfork.softhsm \
-@@ -33,7 +35,9 @@ dist_check_SCRIPTS = \
- 	ec-check-privkey.softhsm \
+@@ -35,6 +36,7 @@ dist_check_SCRIPTS = \
+ 	ec-copy.softhsm \
+ 	fork-change-slot.softhsm \
+ 	case-insensitive.softhsm \
++	keygen.softhsm \
  	pkcs11-uri-without-token.softhsm \
- 	search-all-matching-tokens.softhsm \
--	ec-cert-store.softhsm
-+	ec-cert-store.softhsm \
-+	ec-copy.softhsm \
-+	keygen.softhsm
+ 	search-all-matching-tokens.softhsm
  dist_check_DATA = \
- 	rsa-cert.der rsa-prvkey.der rsa-pubkey.der \
- 	ec-cert.der ec-prvkey.der ec-pubkey.der
+diff --git a/tests/ec-no-pubkey.sh b/tests/ec-no-pubkey.sh
+new file mode 100644
+index 0000000..0fc2d8c
+--- /dev/null
++++ b/tests/ec-no-pubkey.sh
+@@ -0,0 +1,122 @@
++#!/bin/sh
++
++# Copyright (C) 2013 Nikos Mavrogiannopoulos
++# Copyright (C) 2019 Anderson Toshiyuki Sasaki
++# Copyright (C) 2019 Red Hat, Inc.
++#
++# This program is free software: you can redistribute it and/or modify
++# it under the terms of the GNU General Public License as published by
++# the Free Software Foundation, either version 3 of the License, or
++# (at your option) any later version.
++#
++# This program is distributed in the hope that it will be useful,
++# but WITHOUT ANY WARRANTY; without even the implied warranty of
++# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
++# GNU General Public License for more details.
++#
++# You should have received a copy of the GNU General Public License
++# along with this program.  If not, see <https://www.gnu.org/licenses/>.
++
++OPENSSL_VERSION=$(./openssl_version | cut -d ' ' -f 2)
++case "${OPENSSL_VERSION}" in
++0.*)
++    echo "EC tests skipped with OpenSSL ${OPENSSL_VERSION}"
++	exit 77
++	;;
++*)
++	;;
++esac
++
++echo "Current directory: $(pwd)"
++echo "Source directory: ${srcdir}"
++echo "Output directory: ${outdir}"
++
++mkdir -p $outdir
++
++for i in /usr/lib64/pkcs11 /usr/lib64/softhsm /usr/lib/x86_64-linux-gnu/softhsm /usr/local/lib/softhsm /opt/local/lib/softhsm /usr/lib/softhsm /usr/lib ;do
++	if test -f "$i/libsofthsm2.so"; then
++		MODULE="$i/libsofthsm2.so"
++		break
++	else
++		if test -f "$i/libsofthsm.so";then
++			MODULE="$i/libsofthsm.so"
++			break
++		fi
++	fi
++done
++
++if (! test -x /usr/bin/pkcs11-tool && ! test -x /usr/local/bin/pkcs11-tool);then
++	exit 77
++fi
++
++init_card () {
++	PIN="$1"
++	PUK="$2"
++
++	if test -x "/usr/bin/softhsm"; then
++		export SOFTHSM_CONF="$outdir/softhsm-testpkcs11.config"
++		SOFTHSM_TOOL="/usr/bin/softhsm"
++	fi
++
++	if test -x "/usr/local/bin/softhsm2-util"; then
++		export SOFTHSM2_CONF="$outdir/softhsm-testpkcs11.config"
++		SOFTHSM_TOOL="/usr/local/bin/softhsm2-util"
++	fi
++
++	if test -x "/opt/local/bin/softhsm2-util"; then
++		export SOFTHSM2_CONF="$outdir/softhsm-testpkcs11.config"
++		SOFTHSM_TOOL="/opt/local/bin/softhsm2-util"
++	fi
++
++	if test -x "/usr/bin/softhsm2-util"; then
++		export SOFTHSM2_CONF="$outdir/softhsm-testpkcs11.config"
++		SOFTHSM_TOOL="/usr/bin/softhsm2-util"
++	fi
++
++	if test -z "${SOFTHSM_TOOL}"; then
++		echo "Could not find softhsm(2) tool"
++		exit 77
++	fi
++
++	if test -n "${SOFTHSM2_CONF}"; then
++		rm -rf $outdir/softhsm-testpkcs11.db
++		mkdir -p $outdir/softhsm-testpkcs11.db
++		echo "objectstore.backend = file" > "${SOFTHSM2_CONF}"
++		echo "directories.tokendir = $outdir/softhsm-testpkcs11.db" >> "${SOFTHSM2_CONF}"
++	else
++		rm -rf $outdir/softhsm-testpkcs11.db
++		echo "0:$outdir/softhsm-testpkcs11.db" > "${SOFTHSM_CONF}"
++	fi
++
++
++	echo -n "* Initializing smart card... "
++	${SOFTHSM_TOOL} --init-token --slot 0 --label "libp11-test" --so-pin "${PUK}" --pin "${PIN}" >/dev/null
++	if test $? = 0; then
++		echo ok
++	else
++		echo failed
++		exit 1
++	fi
++}
++
++PIN=1234
++PUK=1234
++init_card $PIN $PUK
++
++# generate key in token
++pkcs11-tool -p $PIN --module $MODULE -d 01020304 -a server-key -l -w ${srcdir}/ec-privkey.der -y privkey >/dev/null
++if test $? != 0;then
++	exit 1;
++fi
++
++pkcs11-tool -p $PIN --module $MODULE -d 01020304 -a server-key -l -w ${srcdir}/ec-cert.der -y cert >/dev/null
++if test $? != 0;then
++	exit 1;
++fi
++
++openssl x509 -in ${srcdir}/ec-cert.der -inform DER -out ${outdir}/ec-cert.pem -outform PEM
++
++echo "***************"
++echo "Listing objects"
++echo "***************"
++pkcs11-tool -p $PIN --module $MODULE -l -O
 diff --git a/tests/keygen.c b/tests/keygen.c
 new file mode 100644
 index 0000000..6ed8f6f
