base: cryptfs: additions to online re-encryption
The PKCS#11 database could have been cleared causing the KEK to be
lost. Check if that is the case before opening the volume.

If on-line reencryption has started and the volume is closed, it can't
be open again until re-encryption as been completed (offline)

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

diff --git a/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs b/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs
--- a/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs
+++ b/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs
@@ -117,23 +117,40 @@ cryptfs_run() {
 			cat /run/cryptsetup/passphrase | cryptsetup luksOpen ${root_dev} ${luks_name}
 			cat /run/cryptsetup/passphrase | cryptsetup -v reencrypt --resume-only ${root_dev}
 			cryptsetup close ${luks_name}
+		else
+			# Complete re-encryption before opening and mounting
+			msg "${root_dev} encryption not yet finalized, running recovery"
+			yes "YES" | cryptsetup -v repair ${root_dev}
+			! cryptsetup -v reencrypt --resume-only ${root_dev} &&
+				fatal "Unable complete inline re-encryption"
 		fi
 	fi
 
-	! cat /run/cryptsetup/passphrase | cryptsetup luksOpen ${root_dev} ${luks_name} &&
-		fatal "Unable to open the LUKS partition ${root_dev}, invalid passphrase / ${luks_token} token"
+	if ! cryptsetup luksDump ${root_dev} | grep -q "systemd-${luks_token}"; then
+		msg "${luks_token} not enrolled for ${root_dev}"
+		! cat /run/cryptsetup/passphrase | cryptsetup luksOpen ${root_dev} ${luks_name} &&
+			fatal "Unable to open the LUKS partition ${root_dev}"
+	else
+		msg "${luks_token} enrolled for ${root_dev}"
+		cryptfs_check_token_${luks_token}
+		! cryptsetup luksOpen ${root_dev} ${luks_name} &&
+			fatal "Unable to open the LUKS partition ${root_dev}"
+	fi
 
 	e2fsck_check /dev/mapper/${luks_name}
 
+	# If not enrolled
 	if ! cryptsetup luksDump ${root_dev} | grep -q "systemd-${luks_token}"; then
 		msg "Enrolling LUKS2 keyslot based on ${luks_token} token"
 		cryptfs_enroll_${luks_token} ${root_dev}
 	fi
 
-	if ! cryptsetup luksDump ${root_dev} | grep -q "online-reencrypt"; then
+	# If enrolled
+	if cryptsetup luksDump ${root_dev} | grep -q "systemd-${luks_token}"; then
 		# CI encrypted uses keyslot 31 by default, forcing enrolled key to be 0
 		if cryptsetup luksDump ${root_dev} | grep -q "0: luks"; then
-			cryptsetup reencrypt --init-only ${root_dev}
+			! cryptsetup reencrypt --init-only ${root_dev} &&
+				fatal "Unable to start online reencryption"
 		fi
 	fi
 
diff --git a/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs_pkcs11 b/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs_pkcs11
--- a/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs_pkcs11
+++ b/meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs_pkcs11
@@ -1,8 +1,16 @@
 # Copyright (C) 2022 Fondries.IO
 # SPDX-License-Identifier: MIT
 
+MODULE=/usr/lib/libckteec.so.0
+
 cryptfs_check_pkcs11() {
 	[ ! -c /dev/tee0 ] && fatal "Linux OP-TEE device node not found"
+}
+
+cryptfs_check_token_pkcs11() {
+	if ! pkcs11-tool --module $MODULE --token-label lmp --list-objects | grep -q "9d"; then
+		fatal "PKCS11 certificate not found!"
+	fi
 }
 
 cryptfs_pre_pkcs11() {
@@ -20,7 +28,6 @@ cryptfs_post_pkcs11() {
 cryptfs_enroll_pkcs11() {
 	root_dev=$1
 
-	MODULE=/usr/lib/libckteec.so.0
 	# We force usage of the second slot (1) to avoid clashes with lmp-device-register
 	pkcs11-tool --module $MODULE --init-token --slot 1 --label lmp --so-pin ""
 	pkcs11-tool --module $MODULE --token-label lmp --init-pin --so-pin foo --pin user:ef0180a3-13f3-5d1c-b7f5-888c0e21059a
